name = "fortarray"
version = "0.1.0"
license = "MIT"
author = "Fortarray contributors"
maintainer = "krystophny@github"
copyright = "2026 Fortarray contributors"

[build]
auto-executables = false
auto-examples = false
auto-tests = true
module-naming = false
link = ["pthread"]

[install]
library = true

[library]
source-dir = "src"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
fortio = { git = "https://github.com/lazy-fortran/fortio.git", rev = "b6a0c57e7a7577612637ed1619c3bc50d26c2556" }
