name = "fortarray"
version = "0.1.0"
license = "MIT"
author = "FortArray Contributors"
maintainer = "krystophny@github"
copyright = "2025 FortArray Contributors"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
link = ["netcdff", "netcdf"]

[install]
library = false

[dependencies]
fortplot = { git = "https://github.com/krystophny/fortplot.git" }
netcdf = "*"

